# Generated by Django 3.1.5 on 2021-01-09 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_token', models.CharField(default='', max_length=100, null=True)),
                ('store_logo', models.CharField(default='', max_length=100, null=True)),
                ('store_header', models.CharField(default='', max_length=100, null=True)),
                ('store_footer', models.CharField(default='', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, null=True)),
                ('email', models.CharField(default='', max_length=100, null=True)),
                ('token', models.CharField(default='', max_length=100, null=True)),
            ],
        ),
    ]
