# Generated by Django 3.1.5 on 2021-01-15 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomFonts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_url', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('font_name', models.CharField(blank=True, default='', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_token', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('body_tag', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('h1_tag', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('h2_tag', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('h3_tag', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('h4_tag', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('h5_tag', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('h6_tag', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('p_tag', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('block_tag', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('li_tag', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('a_tag', models.CharField(blank=True, default='', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, null=True)),
                ('email', models.CharField(default='', max_length=100, null=True)),
                ('token', models.CharField(default='', max_length=100, null=True)),
            ],
        ),
    ]
