# Generated by Django 3.1.5 on 2021-01-23 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customfonts',
            name='public_url',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
