# Generated by Django 3.1.5 on 2021-01-10 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settings',
            old_name='store_footer',
            new_name='a_tag',
        ),
        migrations.RenameField(
            model_name='settings',
            old_name='store_header',
            new_name='block_tag',
        ),
        migrations.RenameField(
            model_name='settings',
            old_name='store_logo',
            new_name='body_tag',
        ),
        migrations.AddField(
            model_name='settings',
            name='h1_tag',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='h2_tag',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='h3_tag',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='h4_tag',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='h5_tag',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='h6_tag',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='li_tag',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='p_tag',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
