# Generated by Django 3.1.5 on 2021-01-18 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customfonts',
            name='custom_classes',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
