# Generated by Django 3.1.5 on 2021-01-24 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_customfonts_public_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='acccess_token',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
