# Generated by Django 3.1.5 on 2021-01-24 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_store_acccess_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='acccess_token',
        ),
    ]
