# Generated by Django 3.1.5 on 2021-01-24 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_store_acccess_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='charge_id',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='upgrade_status',
            field=models.CharField(blank=True, default='inactive', max_length=100, null=True),
        ),
    ]
