# Generated by Django 3.1.5 on 2021-02-09 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_customclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='review',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
