# Generated by Django 3.2.7 on 2021-09-30 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_store_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomClass',
        ),
        migrations.DeleteModel(
            name='CustomFonts',
        ),
        migrations.DeleteModel(
            name='Settings',
        ),
        migrations.DeleteModel(
            name='Store',
        ),
    ]
